# Form implementation generated from reading ui file 'voting_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_voting_window(object):
    def setupUi(self, voting_window):
        voting_window.setObjectName("voting_window")
        voting_window.resize(274, 585)
        voting_window.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=voting_window)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(70, 380, 113, 32))
        self.exit_button.setObjectName("exit_button")
        self.summary_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.summary_button.setGeometry(QtCore.QRect(50, 320, 151, 32))
        self.summary_button.setObjectName("summary_button")
        self.reset_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(70, 350, 113, 32))
        self.reset_button.setObjectName("reset_button")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(60, 10, 141, 20))
        self.title.setObjectName("title")
        self.id_enter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_enter.setGeometry(QtCore.QRect(100, 80, 113, 21))
        self.id_enter.setObjectName("id_enter")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(9, 80, 91, 20))
        self.id_label.setObjectName("id_label")
        self.candidate_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidate_label.setGeometry(QtCore.QRect(70, 140, 121, 20))
        self.candidate_label.setObjectName("candidate_label")
        self.john_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.john_button.setGeometry(QtCore.QRect(60, 180, 100, 20))
        self.john_button.setObjectName("john_button")
        self.jane_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jane_button.setGeometry(QtCore.QRect(60, 210, 100, 20))
        self.jane_button.setObjectName("jane_button")
        self.other_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.other_button.setGeometry(QtCore.QRect(10, 240, 100, 20))
        self.other_button.setObjectName("other_button")
        self.other_lineedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.other_lineedit.setGeometry(QtCore.QRect(80, 240, 113, 21))
        self.other_lineedit.setObjectName("other_lineedit")
        self.confirm_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(70, 290, 113, 32))
        self.confirm_button.setObjectName("confirm_button")
        voting_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=voting_window)
        self.statusbar.setObjectName("statusbar")
        voting_window.setStatusBar(self.statusbar)

        self.retranslateUi(voting_window)
        QtCore.QMetaObject.connectSlotsByName(voting_window)

    def retranslateUi(self, voting_window):
        _translate = QtCore.QCoreApplication.translate
        voting_window.setWindowTitle(_translate("voting_window", "MainWindow"))
        self.exit_button.setText(_translate("voting_window", "Exit"))
        self.summary_button.setText(_translate("voting_window", "Show Voting Count"))
        self.reset_button.setText(_translate("voting_window", "Reset Count"))
        self.title.setText(_translate("voting_window", "Voting for Candidates"))
        self.id_label.setText(_translate("voting_window", "Enter Your ID:"))
        self.candidate_label.setText(_translate("voting_window", "Vote one candidate"))
        self.john_button.setText(_translate("voting_window", "John"))
        self.jane_button.setText(_translate("voting_window", "Jane"))
        self.other_button.setText(_translate("voting_window", "Other:"))
        self.confirm_button.setText(_translate("voting_window", "Confirm Vote"))
